module.exports = {
  CONFIGURE_SARAH: 'configure_sarah',
  GOOD_KEYWORDS: 'good_keywords',
  BAD_KEYWORDS: 'bad_keywords',
  ADD_GOOD_KEYWORDS: 'add_good_keywords',
  ADD_BAD_KEYWORDS: 'add_bad_keywords',
  LIST_GOOD_KEYWORDS: 'list_good_keywords',
  LIST_BAD_KEYWORDS: 'list_bad_keywords',
  DONE_ADDING_KEYWORDS: 'done_adding_keywords',
  NOT_DONE_ADDING_KEYWORDS: 'not_done_adding_keywords',
  PERCENTAGE_OF_CONFIDENCE: 'percentage_of_confidence',
  WHAT_TO_MONITOR: 'what_to_monitor',
  ANALYZE_WHAT: 'analyze_what',
  WHAT_ACTION_TO_DO: 'what_action_to_do',
  TRAIN_THE_BOT_BLACK_LIST: 'train_the_bot_black_list',
  TRAIN_THE_BOT_WHITE_LIST: 'train_the_bot_white_list',
  GET_DASHBOARD_LINK: 'get_dashboard_link',
  CONTENT_SEARCH: 'content_search',
  GET_STARTED_PAYLOAD: 'GET_STARTED_PAYLOAD',
  NORMAL: 'normal',
};
